/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    news: News;
    products: Product;
    partners: Partner;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Quản lý trang website — admin tự tạo URL, chọn template và sắp xếp section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title?: string | null;
  /**
   * Dùng để định danh page trong CMS. Riêng Trang chủ dùng "home"; URL public là /vi hoặc /en.
   */
  slug: string;
  /**
   * Legacy field, không dùng trong admin. Page hiện render bằng layout blocks.
   */
  template?: ('home' | 'builder' | 'about' | 'projects') | null;
  /**
   * Dùng cho Trang chủ và các trang page-builder. Giữ cùng cấu trúc block với Home Page cũ.
   */
  layout?:
    | (
        | {
            /**
             * Chọn kiểu layout. Mỗi biến thể tương ứng 1 phiên bản homepage trong design_3.pen.
             */
            variant?: ('corporate' | 'modernSplit' | 'dataGrid' | 'modernRounded' | 'ultraModern') | null;
            /**
             * Ảnh hiển thị ở cột phải của hero khi variant = Modern Split.
             */
            heroImage?: (number | null) | Media;
            heroImageURL?: string | null;
            badgeText?: string | null;
            title: string;
            subtitle?: string | null;
            backgroundType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: (number | null) | Media;
            trustPartners?:
              | {
                  name: string;
                  logo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Để trống để ẩn thanh thống kê. Item đầu tiên có thể dùng màu khác.
             */
            stats?:
              | {
                  value: number;
                  suffix?: string | null;
                  labelTop?: string | null;
                  labelBottom?: string | null;
                  /**
                   * Nhập mã màu HEX. VD: #B92C32 cho màu đỏ, #FFFFFF cho màu trắng.
                   */
                  numberColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            backgroundType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            /**
             * Dùng khi chưa upload ảnh.
             */
            backgroundImageURL?: string | null;
            /**
             * Upload file MP4 hoặc WebM. Video sẽ tự phát, tắt tiếng, lặp lại.
             */
            backgroundVideo?: (number | null) | Media;
            /**
             * Khuyên dùng — hiện trên thiết bị không hỗ trợ autoplay hoặc khi video đang tải.
             */
            posterImage?: (number | null) | Media;
            /**
             * Chiều cao trên desktop. Mobile sẽ tự scale xuống.
             */
            height?: number | null;
            /**
             * 0 = không overlay, 100 = tối hoàn toàn.
             */
            overlayOpacity?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            /**
             * Text lớn phía trên mô tả. Hiển thị kèm thanh đỏ bên trái.
             */
            eyebrow?: string | null;
            /**
             * Đoạn văn giới thiệu hiển thị dưới tiêu đề.
             */
            body?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Tối thiểu 1 ảnh. Nếu có từ 2 ảnh trở lên sẽ hiện carousel với nút mũi tên.
             */
            images?:
              | {
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Carousel tự chuyển sau mỗi 4 giây. Tạm dừng khi hover.
             */
            autoPlay?: boolean | null;
            /**
             * Chỉ có hiệu lực khi "Tự động chuyển ảnh" được bật.
             */
            autoPlayInterval?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'welcomeIntro';
          }
        | {
            title: string;
            /**
             * Danh sách breadcrumb. Item cuối không cần href.
             */
            breadcrumbs?:
              | {
                  label: string;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Dùng khi không set Breadcrumbs ở trên. Nếu để trống sẽ dùng tiêu đề trang.
             */
            breadcrumbLabel?: string | null;
            height?: ('sm' | 'md' | 'lg' | 'xl') | null;
            backgroundImage?: (number | null) | Media;
            /**
             * Dùng khi chưa upload ảnh.
             */
            backgroundImageURL?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            sidebarGroups?:
              | {
                  title: string;
                  titleHref?: string | null;
                  items?:
                    | {
                        label: string;
                        href: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            sections?:
              | {
                  id: string;
                  /**
                   * Chọn layout gần với design của section này để frontend render đúng.
                   */
                  variant?:
                    | ('intro' | 'cards' | 'gallery' | 'itemGrid' | 'splitMedia' | 'documentList' | 'tabbedDocuments')
                    | null;
                  title: string;
                  /**
                   * Dùng cho section có 1 đoạn mô tả ngắn phía trên grid/list.
                   */
                  body?: string | null;
                  /**
                   * Dùng cho section kiểu intro hoặc media + text.
                   */
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  columns?: ('2' | '3' | '4') | null;
                  imagePosition?: ('left' | 'right') | null;
                  /**
                   * Intro và splitMedia thường dùng 1 ảnh; gallery dùng nhiều ảnh.
                   */
                  images?:
                    | {
                        image?: (number | null) | Media;
                        imageURL?: string | null;
                        alt?: string | null;
                        caption?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Mỗi tab là một danh mục (vd: Chứng nhận, Tài liệu). Mỗi tab chứa nhiều file tải về.
                   */
                  tabs?:
                    | {
                        tabTitle: string;
                        files?:
                          | {
                              title: string;
                              file?: (number | null) | Media;
                              fileURL?: string | null;
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Dùng cho product cards, service cards, office cards, certification cards và danh sách tài liệu.
                   */
                  items?:
                    | {
                        title: string;
                        subtitle?: string | null;
                        description?: string | null;
                        meta?: string | null;
                        icon?: string | null;
                        image?: (number | null) | Media;
                        imageURL?: string | null;
                        alt?: string | null;
                        href?: string | null;
                        buttonLabel?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutContent';
          }
        | {
            id?: string | null;
            title: string;
            body?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            imagePosition?: ('left' | 'right') | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'contentIntro';
          }
        | {
            title: string;
            body?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  title: string;
                  subtitle?: string | null;
                  description?: string | null;
                  meta?: string | null;
                  icon?: string | null;
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  href?: string | null;
                  buttonLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureCards';
          }
        | {
            title: string;
            id?: string | null;
            body?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            title: string;
            id?: string | null;
            body?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  title: string;
                  subtitle?: string | null;
                  description?: string | null;
                  meta?: string | null;
                  icon?: string | null;
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  href?: string | null;
                  buttonLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'infoGrid';
          }
        | {
            id?: string | null;
            title: string;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            imagePosition?: ('left' | 'right') | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'mediaTextSplit';
          }
        | {
            title: string;
            id?: string | null;
            body?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            items?:
              | {
                  title: string;
                  subtitle?: string | null;
                  description?: string | null;
                  meta?: string | null;
                  icon?: string | null;
                  image?: (number | null) | Media;
                  imageURL?: string | null;
                  alt?: string | null;
                  href?: string | null;
                  buttonLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockName?: string | null;
            blockType: 'documentList';
          }
        | {
            sourceMode?: ('latest' | 'manual') | null;
            limit?: number | null;
            projects?: (number | Project)[] | null;
            parentCategories?:
              | {
                  label: string;
                  value: 'electrical-automation' | 'digitalization' | 'industrial-services' | 'measurement';
                  industryFilters?:
                    | {
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsListing';
          }
        | {
            /**
             * Bento: 5 cards đầu; Alternating: tất cả cards xen kẽ; Cards: 3 cards mặc định.
             */
            variant?: ('cards' | 'bento' | 'alternating') | null;
            title?: string | null;
            subtitle?: string | null;
            /**
             * Mỗi item tương ứng một card bên dưới section. Home hiện dùng 3 card như thiết kế.
             */
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Dùng khi chưa upload ảnh. Nếu upload ảnh, frontend sẽ ưu tiên ảnh upload.
                   */
                  imageURL?: string | null;
                  href?: string | null;
                  buttonLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            title?: string | null;
            /**
             * Featured là layout mặc định (home v1). Grid dùng cho home v2.
             */
            displayMode?: ('featured' | 'grid') | null;
            viewAll?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Latest: tự lấy bài mới nhất từ collection News. Manual: ưu tiên các bài được chọn bên dưới.
             */
            sourceMode?: ('latest' | 'manual') | null;
            /**
             * UI hiện tại cố định 3 bài: 1 bài lớn bên trái và 2 bài nhỏ bên phải.
             */
            count?: number | null;
            /**
             * Dùng khi nguồn bài viết là Manual. Nếu để trống sẽ fallback về bài mới nhất.
             */
            featuredNews?: (number | null) | News;
            /**
             * Dùng khi nguồn bài viết là Manual. Nếu để trống sẽ fallback về các bài mới tiếp theo.
             */
            secondaryNews?: (number | News)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            /**
             * Grid: dùng nền tối + tabs. Alternating & List: nền trắng, không có tabs.
             */
            variant?: ('grid' | 'alternating' | 'list') | null;
            title?: string | null;
            /**
             * Nhập mã màu HEX. VD: #0B1221 cho nền navy tối, #FFFFFF cho nền trắng.
             */
            backgroundColor?: string | null;
            /**
             * Chọn "Chữ đen" khi nền section là màu sáng (trắng, xám nhạt, v.v.) để đảm bảo text dễ đọc.
             */
            textTheme?: ('dark' | 'light') | null;
            viewAll?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Latest: tự lấy dự án featured mới nhất. Manual: ưu tiên các dự án được chọn bên dưới.
             */
            sourceMode?: ('latest' | 'manual') | null;
            /**
             * UI hiện tại dùng grid 2x2, tối đa 4 dự án.
             */
            count?: number | null;
            /**
             * Dùng khi nguồn dự án là Manual. Nếu để trống sẽ fallback về dự án featured mới nhất.
             */
            featuredProjects?: (number | Project)[] | null;
            /**
             * Các pill filter phía trên grid. Label hiển thị trên UI; value nên khớp nhóm hiển thị của project.
             */
            tabs?:
              | {
                  label: string;
                  value: 'energy' | 'electrical' | 'automation' | 'bms';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProjects';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            backgroundColor?: string | null;
            /**
             * 4 ảnh theo layout design: trái cao, giữa 2 ảnh nhỏ, phải cao.
             */
            images?:
              | {
                  alt?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Dùng khi chưa upload ảnh. Nếu upload ảnh, frontend ưu tiên ảnh upload.
                   */
                  imageURL?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            sourceMode?: ('latest' | 'manual') | null;
            count?: number | null;
            featuredProducts?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'products';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            backgroundColor?: string | null;
            gradientFrom?: string | null;
            gradientMiddle?: string | null;
            gradientTo?: string | null;
            accentColor?: string | null;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            title?: string | null;
            sourceMode?: ('latest' | 'manual') | null;
            count?: number | null;
            partners?: (number | Partner)[] | null;
            fallbackBrands?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandLogos';
          }
        | {
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  titleLabel?: string | null;
  title: {
    vi: string;
    en?: string | null;
  };
  slug: string;
  category: 'electrical-automation' | 'digitalization' | 'measurement' | 'industrial-services';
  industry?:
    | (
        | 'oil-gas'
        | 'fertilizer-chemical'
        | 'power'
        | 'cement-mining'
        | 'steel'
        | 'food-beverage'
        | 'consumer-goods'
        | 'water'
        | 'port'
        | 'other'
      )
    | null;
  /**
   * Dùng cho badge và tab filter ở block Dự án tiêu biểu trên Home.
   */
  featuredType?: ('energy' | 'electrical' | 'automation' | 'bms') | null;
  featuredBadgeLabel?: string | null;
  /**
   * Nhập mã màu HEX. VD: #B92C32, #2b358c, #6366F1.
   */
  featuredBadgeColor?: string | null;
  thumbnail: number | Media;
  customerName?: {
    vi?: string | null;
    en?: string | null;
  };
  customerAddress?: string | null;
  location?: string | null;
  year?: number | null;
  detailHeroImage?: (number | null) | Media;
  introImage?: (number | null) | Media;
  summary?: {
    vi?: string | null;
    en?: string | null;
  };
  intro?: {
    vi?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  solutions?: {
    vi?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  customerReasons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  resultItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  results?: {
    vi?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  titleLabel?: string | null;
  title: {
    vi: string;
    en?: string | null;
  };
  slug: string;
  publishedAt: string;
  thumbnail: number | Media;
  excerpt?: {
    vi?: string | null;
    en?: string | null;
  };
  content?: {
    vi?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  tags?: ('Tin tức' | 'Sự kiện' | 'Hội thảo' | 'Thông cáo')[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  nameLabel?: string | null;
  name: {
    vi: string;
    en?: string | null;
  };
  slug: string;
  category: 'automation' | 'measurement' | 'industrial-valve' | 'electrical' | 'motor' | 'sensor';
  /**
   * VD: Valve & Actuator, Motor & Drive, Sensor & Instrument.
   */
  displayCategory?: string | null;
  thumbnail: number | Media;
  description?: {
    vi?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  brand?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: {
    vi: string;
    en?: string | null;
  };
  slug: string;
  category?: ('electrical-automation' | 'digitalization' | 'measurement' | 'industrial-services') | null;
  icon?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  summary?: {
    vi?: string | null;
    en?: string | null;
  };
  content?: {
    vi?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              heroImage?: T;
              heroImageURL?: T;
              badgeText?: T;
              title?: T;
              subtitle?: T;
              backgroundType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              trustPartners?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    id?: T;
                  };
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    labelTop?: T;
                    labelBottom?: T;
                    numberColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroBanner?:
          | T
          | {
              backgroundType?: T;
              backgroundImage?: T;
              backgroundImageURL?: T;
              backgroundVideo?: T;
              posterImage?: T;
              height?: T;
              overlayOpacity?: T;
              id?: T;
              blockName?: T;
            };
        welcomeIntro?:
          | T
          | {
              eyebrow?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    id?: T;
                  };
              autoPlay?: T;
              autoPlayInterval?: T;
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              title?: T;
              breadcrumbs?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              breadcrumbLabel?: T;
              height?: T;
              backgroundImage?: T;
              backgroundImageURL?: T;
              id?: T;
              blockName?: T;
            };
        aboutContent?:
          | T
          | {
              sidebarGroups?:
                | T
                | {
                    title?: T;
                    titleHref?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              sections?:
                | T
                | {
                    id?: T;
                    variant?: T;
                    title?: T;
                    body?: T;
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    columns?: T;
                    imagePosition?: T;
                    images?:
                      | T
                      | {
                          image?: T;
                          imageURL?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                        };
                    tabs?:
                      | T
                      | {
                          tabTitle?: T;
                          files?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileURL?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    items?:
                      | T
                      | {
                          title?: T;
                          subtitle?: T;
                          description?: T;
                          meta?: T;
                          icon?: T;
                          image?: T;
                          imageURL?: T;
                          alt?: T;
                          href?: T;
                          buttonLabel?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        contentIntro?:
          | T
          | {
              id?: T;
              title?: T;
              body?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              imagePosition?: T;
              images?:
                | T
                | {
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              title?: T;
              body?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    meta?: T;
                    icon?: T;
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    href?: T;
                    buttonLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              id?: T;
              body?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              images?:
                | T
                | {
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        infoGrid?:
          | T
          | {
              title?: T;
              id?: T;
              body?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    meta?: T;
                    icon?: T;
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    href?: T;
                    buttonLabel?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        mediaTextSplit?:
          | T
          | {
              id?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              imagePosition?: T;
              images?:
                | T
                | {
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        documentList?:
          | T
          | {
              title?: T;
              id?: T;
              body?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    meta?: T;
                    icon?: T;
                    image?: T;
                    imageURL?: T;
                    alt?: T;
                    href?: T;
                    buttonLabel?: T;
                    id?: T;
                  };
              blockName?: T;
            };
        projectsListing?:
          | T
          | {
              sourceMode?: T;
              limit?: T;
              projects?: T;
              parentCategories?:
                | T
                | {
                    label?: T;
                    value?: T;
                    industryFilters?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              variant?: T;
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    imageURL?: T;
                    href?: T;
                    buttonLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              displayMode?: T;
              viewAll?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              sourceMode?: T;
              count?: T;
              featuredNews?: T;
              secondaryNews?: T;
              id?: T;
              blockName?: T;
            };
        featuredProjects?:
          | T
          | {
              variant?: T;
              title?: T;
              backgroundColor?: T;
              textTheme?: T;
              viewAll?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              sourceMode?: T;
              count?: T;
              featuredProjects?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundColor?: T;
              images?:
                | T
                | {
                    alt?: T;
                    image?: T;
                    imageURL?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              title?: T;
              subtitle?: T;
              sourceMode?: T;
              count?: T;
              featuredProducts?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundColor?: T;
              gradientFrom?: T;
              gradientMiddle?: T;
              gradientTo?: T;
              accentColor?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        brandLogos?:
          | T
          | {
              title?: T;
              sourceMode?: T;
              count?: T;
              partners?: T;
              fallbackBrands?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  titleLabel?: T;
  title?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  slug?: T;
  category?: T;
  industry?: T;
  featuredType?: T;
  featuredBadgeLabel?: T;
  featuredBadgeColor?: T;
  thumbnail?: T;
  customerName?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  customerAddress?: T;
  location?: T;
  year?: T;
  detailHeroImage?: T;
  introImage?: T;
  summary?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  intro?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  solutions?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  customerReasons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  resultItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  results?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  titleLabel?: T;
  title?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  slug?: T;
  publishedAt?: T;
  thumbnail?: T;
  excerpt?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  content?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  nameLabel?: T;
  name?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  slug?: T;
  category?: T;
  displayCategory?: T;
  thumbnail?: T;
  description?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  brand?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  slug?: T;
  category?: T;
  icon?: T;
  thumbnail?: T;
  summary?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  content?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Deprecated: chỉ giữ tạm để migrate dữ liệu sang Pages > home
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  layout?:
    | (
        | {
            /**
             * Chọn kiểu layout. Mỗi biến thể tương ứng 1 phiên bản homepage trong design_3.pen.
             */
            variant?: ('corporate' | 'modernSplit' | 'dataGrid' | 'modernRounded' | 'ultraModern') | null;
            /**
             * Ảnh hiển thị ở cột phải của hero khi variant = Modern Split.
             */
            heroImage?: (number | null) | Media;
            heroImageURL?: string | null;
            badgeText?: string | null;
            title: string;
            subtitle?: string | null;
            backgroundType?: ('image' | 'video') | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: (number | null) | Media;
            trustPartners?:
              | {
                  name: string;
                  logo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Để trống để ẩn thanh thống kê. Item đầu tiên có thể dùng màu khác.
             */
            stats?:
              | {
                  value: number;
                  suffix?: string | null;
                  labelTop?: string | null;
                  labelBottom?: string | null;
                  /**
                   * Nhập mã màu HEX. VD: #B92C32 cho màu đỏ, #FFFFFF cho màu trắng.
                   */
                  numberColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Bento: 5 cards đầu; Alternating: tất cả cards xen kẽ; Cards: 3 cards mặc định.
             */
            variant?: ('cards' | 'bento' | 'alternating') | null;
            title?: string | null;
            subtitle?: string | null;
            /**
             * Mỗi item tương ứng một card bên dưới section. Home hiện dùng 3 card như thiết kế.
             */
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Dùng khi chưa upload ảnh. Nếu upload ảnh, frontend sẽ ưu tiên ảnh upload.
                   */
                  imageURL?: string | null;
                  href?: string | null;
                  buttonLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            title?: string | null;
            /**
             * Featured là layout mặc định (home v1). Grid dùng cho home v2.
             */
            displayMode?: ('featured' | 'grid') | null;
            viewAll?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Latest: tự lấy bài mới nhất từ collection News. Manual: ưu tiên các bài được chọn bên dưới.
             */
            sourceMode?: ('latest' | 'manual') | null;
            /**
             * UI hiện tại cố định 3 bài: 1 bài lớn bên trái và 2 bài nhỏ bên phải.
             */
            count?: number | null;
            /**
             * Dùng khi nguồn bài viết là Manual. Nếu để trống sẽ fallback về bài mới nhất.
             */
            featuredNews?: (number | null) | News;
            /**
             * Dùng khi nguồn bài viết là Manual. Nếu để trống sẽ fallback về các bài mới tiếp theo.
             */
            secondaryNews?: (number | News)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            /**
             * Grid: dùng nền tối + tabs. Alternating & List: nền trắng, không có tabs.
             */
            variant?: ('grid' | 'alternating' | 'list') | null;
            title?: string | null;
            /**
             * Nhập mã màu HEX. VD: #0B1221 cho nền navy tối, #FFFFFF cho nền trắng.
             */
            backgroundColor?: string | null;
            /**
             * Chọn "Chữ đen" khi nền section là màu sáng (trắng, xám nhạt, v.v.) để đảm bảo text dễ đọc.
             */
            textTheme?: ('dark' | 'light') | null;
            viewAll?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Latest: tự lấy dự án featured mới nhất. Manual: ưu tiên các dự án được chọn bên dưới.
             */
            sourceMode?: ('latest' | 'manual') | null;
            /**
             * UI hiện tại dùng grid 2x2, tối đa 4 dự án.
             */
            count?: number | null;
            /**
             * Dùng khi nguồn dự án là Manual. Nếu để trống sẽ fallback về dự án featured mới nhất.
             */
            featuredProjects?: (number | Project)[] | null;
            /**
             * Các pill filter phía trên grid. Label hiển thị trên UI; value nên khớp nhóm hiển thị của project.
             */
            tabs?:
              | {
                  label: string;
                  value: 'energy' | 'electrical' | 'automation' | 'bms';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProjects';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            backgroundColor?: string | null;
            /**
             * 4 ảnh theo layout design: trái cao, giữa 2 ảnh nhỏ, phải cao.
             */
            images?:
              | {
                  alt?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Dùng khi chưa upload ảnh. Nếu upload ảnh, frontend ưu tiên ảnh upload.
                   */
                  imageURL?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            sourceMode?: ('latest' | 'manual') | null;
            count?: number | null;
            featuredProducts?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'products';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            backgroundColor?: string | null;
            gradientFrom?: string | null;
            gradientMiddle?: string | null;
            gradientTo?: string | null;
            accentColor?: string | null;
            primaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            title?: string | null;
            sourceMode?: ('latest' | 'manual') | null;
            count?: number | null;
            partners?: (number | Partner)[] | null;
            fallbackBrands?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandLogos';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  header?: {
    logoImage?: (number | null) | Media;
    /**
     * Dùng cho ảnh logo ngoài frontend. Nếu bỏ trống sẽ fallback về logo text.
     */
    logoAlt?: string | null;
    logoText?: string | null;
    phone?: string | null;
    email?: string | null;
    navItems?:
      | {
          label: string;
          /**
           * Nhập path không gồm locale, ví dụ /gioi-thieu.
           */
          href: string;
          children?:
            | {
                label: string;
                /**
                 * Nhập path không gồm locale, ví dụ /gioi-thieu/su-menh.
                 */
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    logoImage?: (number | null) | Media;
    /**
     * Dùng cho ảnh logo footer ngoài frontend. Nếu bỏ trống sẽ fallback về logo text.
     */
    logoAlt?: string | null;
    logoText?: string | null;
    description?: string | null;
    backgroundColor?: string | null;
    accentColor?: string | null;
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                /**
                 * Bỏ trống nếu chỉ muốn hiển thị text; nhập /path, tel: hoặc mailto: nếu là link.
                 */
                href?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
    credit?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              heroImage?: T;
              heroImageURL?: T;
              badgeText?: T;
              title?: T;
              subtitle?: T;
              backgroundType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              trustPartners?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    id?: T;
                  };
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    labelTop?: T;
                    labelBottom?: T;
                    numberColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              variant?: T;
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    imageURL?: T;
                    href?: T;
                    buttonLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              displayMode?: T;
              viewAll?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              sourceMode?: T;
              count?: T;
              featuredNews?: T;
              secondaryNews?: T;
              id?: T;
              blockName?: T;
            };
        featuredProjects?:
          | T
          | {
              variant?: T;
              title?: T;
              backgroundColor?: T;
              textTheme?: T;
              viewAll?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              sourceMode?: T;
              count?: T;
              featuredProjects?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundColor?: T;
              images?:
                | T
                | {
                    alt?: T;
                    image?: T;
                    imageURL?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              title?: T;
              subtitle?: T;
              sourceMode?: T;
              count?: T;
              featuredProducts?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundColor?: T;
              gradientFrom?: T;
              gradientMiddle?: T;
              gradientTo?: T;
              accentColor?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        brandLogos?:
          | T
          | {
              title?: T;
              sourceMode?: T;
              count?: T;
              partners?: T;
              fallbackBrands?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        logoImage?: T;
        logoAlt?: T;
        logoText?: T;
        phone?: T;
        email?: T;
        navItems?:
          | T
          | {
              label?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logoImage?: T;
        logoAlt?: T;
        logoText?: T;
        description?: T;
        backgroundColor?: T;
        accentColor?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        copyright?: T;
        credit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}